### ISSUE TITLE
Protocol specs

### ISSUE THREAD

**Issue by ChronosXYZ** [Dx18/GeoBattleServer#1]
Can you provide protocol specification of your game? I liked this project (you also won first place in the "Game Application" nomination of the competition "IT school chooses the strongest"). It would be nice to have documentation :)

**Comment by ChronosXYZ** [comment]
If you provide this, it will be very easy implement this server on native language (Golang/Dlang/Vlang /whatever).

**Comment by Dx18** [comment]
Protocol specification: https://github.com/Dx18/GeoBattleDocs

**Comment by ChronosXYZ** [comment]
Thanks.
